#!/bin/bash

set -euo pipefail

declare -r namespace=lupusmichaelis
declare -r image_name="$1"
declare -r image_version="$2"

declare -r full_image_name="$namespace/$image_name:$image_version"
declare -r image_tag="$namespace/$image_name@$image_version"

git clone /dev-tools.git /dev-tools
git -c advice.detachedHead=false checkout "$image_tag"
cp /dev-tools.env /dev-tools/.env

exec docker compose --env-file=/dev-tools/.env -f /dev-tools/build/docker-compose.yml build --progress plain "$image_name"
