services:
  - docker:20.10.16-dind

builder:
  image: docker:20.10.16
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1
  before_script:
    - apk update && apk add bash curl git util-linux
  script:
    - ./bin/image-builder make-all
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pusher:
  image: docker:20.10.16
  needs:
    - builder
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1
  before_script:
    - apk update && apk add bash curl git util-linux yq
  script:
    # Add those variables to "Settings > CICD > Variables"
    - printf '%b' "$DOCKER_REGISTRY_PASSWORD" | docker login --username="$DOCKER_REGISTRY_USER" --password-stdin
    - ./bin/image-builder push-all-latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
