#!/bin/bash -xe

. env-dist

realm=$USER

for build in \
	alpine \
	\
    alpine-postfix \
    alpine-lighttpd \
	\
    alpine-php7 \
	\
    alpine-nodejs \
    alpine-react \
    alpine-ts \
    alpine-react-ts \
	\
    alpine-elm-0.19 \
	\
    debian-buster-node \
    debian-elm-0.18 \
    debian-elm-0.19
do
    docker build --build-arg UID --build-arg USER_ALIAS -t $realm/$build build/$build
done

build=alpine-mariadb
docker build \
    --build-arg MYSQL_USER_NAME=my_user \
    --build-arg MYSQL_USER_PASSWORD='' \
    --build-arg MYSQL_USER_DATABASE=my_space \
    -t $realm/$build \
    build/$build
