#!/usr/bin/env bash

[[ -z "$DEBUG" ]] \
	|| set -x

docker-sign()
{
	local -r name="$1"
	local -r version="$2"

	docker trust sign "lupusmichaelis/$name:$version"
}

yq()
{
	docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}

docker-compose -f builder.docker-compose.yml build \
    && cat builder.docker-compose.yml \
        | yq e '.services.*.image' - \
        | xargs -n 1 docker trust sign \
    && docker-compose -f builder.docker-compose.yml push
