##############################################################################
#
# Building customized images
#
##############################################################################

version: '3.4'

x-dev-env: &dev-env
    environment:
        - UID=${UID?Please export UID}
        - GID=${GID?Please export GID}
        - USER_ALIAS=${USER_ALIAS?Please export}
    restart: "no"

services:
    ############################################################################
    # Scripts to manage docker images
    #
    igor:
        image: lupusmichaelis/igor:1.0.0
        build:
            context: ./build/igor

    ############################################################################
    # OSes
    #
    alpine:
        <<: *dev-env
        build:
            context: ./build/alpine
        image: lupusmichaelis/alpine:1.0.0

    ############################################################################
    # Web server
    #
    debian-jessie-apache2-php56:
        build: ./build/debian-jessie-apache2-php56
        image: lupusmichaelis/debian-jessie-apache2-php56:1.0.0
        ports:
            - 80:80
        restart: "no"
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro

    alpine-lighttpd:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd
        depends_on:
            - alpine
        environment:
            - USER_ALIAS=root
        image: lupusmichaelis/alpine-lighttpd:1.0.0

    alpine-lighttpd-secure:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd-secure
        depends_on:
            - alpine-lighttpd
        environment:
            - USER_ALIAS=root
        image: lupusmichaelis/alpine-lighttpd-secure:1.0.0

    alpine-lighttpd-proxy:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd-proxy
        depends_on:
            - alpine-lighttpd
            - alpine-php7-fpm
        environment:
            - USER_ALIAS=root
            - BACKEND=alpine-php7-fpm
        image: lupusmichaelis/alpine-lighttpd-proxy:1.0.0

    ############################################################################
    # PHP
    #
    alpine-php7:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
        image: lupusmichaelis/alpine-php7:1.0.0

    alpine-php7-fpm:
        <<: *dev-env
        build:
            context: ./build/alpine-php7-fpm
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-fpm:1.0.0

    alpine-php7-composer:
        <<: *dev-env
        build:
            context: ./build/alpine-php7-composer
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-composer:1.0.0

    ############################################################################
    # MX
    #
    alpine-postfix:
        build:
            context: ./build/alpine-postfix
        environment:
            - USER_ALIAS=kevin
            - UID=${UID?Please export UID}
        image: lupusmichaelis/alpine-postfix:1.0.0

    alpine-postfix-mutt:
        build:
            context: ./build/alpine-postfix-mutt
        environment:
            - USER_ALIAS=kevin
            - UID=${UID?Please export UID}
        image: lupusmichaelis/alpine-postfix-mutt:1.0.0

    ############################################################################
    # Skeleton for Go app
    go-lang:
       build:
           context: ./build/alpine-golang

    ############################################################################
    # Databases
    alpine-mariadb:
        build: ./build/alpine-mariadb
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        image: lupusmichaelis/alpine-mariadb:1.0.0
        restart: "no"

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pyolo', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10

    ############################################################################
    # Node's wonderland
    alpine-nodejs:
        <<: *dev-env
        build:
            context: ./build/alpine-nodejs
        image: lupusmichaelis/alpine-nodejs:1.0.0
        depends_on:
            - alpine

    alpine-react:
        <<: *dev-env
        build:
            context: ./build/alpine-react
        depends_on:
            - alpine-nodejs
        image: lupusmichaelis/alpine-react:1.0.0

    alpine-react-ts:
        <<: *dev-env
        build:
            context: ./build/alpine-react-ts
        depends_on:
            - alpine-react
        image: lupusmichaelis/alpine-react-ts:1.0.0

    debian-buster:
        <<: *dev-env
        build:
            context: ./build/debian-buster
        image: lupusmichaelis/debian-buster:1.0.0

    debian-buster-node:
        <<: *dev-env
        build:
            context: ./build/debian-buster-node
        depends_on:
            - debian-buster
        image: lupusmichaelis/debian-buster-node:1.0.0

    alpine-elm:
        <<: *dev-env
        build:
            context: ./build/alpine-elm
        image: lupusmichaelis/alpine-elm:1.0.0
