#!/bin/bash -xe

. env-dist

realm=$USER

for build in alpine \
    alpine-postfix \
    alpine-lighttpd \
    alpine-nodejs \
    alpine-php7 \
    alpine-ts \
    alpine-react \
    alpine-react-ts \
    alpine-elm-0.19 \
    debian-elm-0.18 \
    debian-elm-0.19
do
    docker build --build-arg UID --build-arg USER_ALIAS -t $realm/$build build/$build
done

build=alpine-mariadb
docker build \
    --build-arg UID \
    --build-arg USER_ALIAS \
    -t $realm/$build \
    build/$build
