##############################################################################
#
# See ./build-images
# This is a compose file to build images
#
##############################################################################

version: '3.4'

x-dev-env: &dev-env
    env_file:
        - .env
    environment:
        - LUPUSMICHAELIS_DEV_UID=${LUPUSMICHAELIS_DEV_UID?Please export LUPUSMICHAELIS_DEV_UID}
        - LUPUSMICHAELIS_DEV_GID=${LUPUSMICHAELIS_DEV_GID?Please export LUPUSMICHAELIS_DEV_GID}
        - LUPUSMICHAELIS_DEV_USER_ALIAS=${LUPUSMICHAELIS_DEV_USER_ALIAS?Please export}

        # Compatibility
        - LP_DEV_UID=${LP_DEV_UID?Please export LP_DEV_UID}
        - LP_DEV_GID=${LP_DEV_GID?Please export LP_DEV_GID}
        - LP_DEV_USER_ALIAS=${LP_DEV_USER_ALIAS?Please export}
    restart: "no"

services:
    ############################################################################
    # Bootstrap to build images
    #
    bootstrap:
        build:
            args:
                LUPUSMICHAELIS_OFFICIAL_ALPINE_VERSION: 3.14.0
            context: ./
        image: lupusmichaelis-bootstrap
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - ./.git:/dev-tools.git:ro

    ############################################################################
    # Scripts to manage docker images
    #
    igor:
        build:
            context: ./build/igor
        image: lupusmichaelis/igor:1.1.3

    ############################################################################
    # OSes
    #
    alpine:
        build:
            context: ./build/alpine
            args:
                LUPUSMICHAELIS_OFFICIAL_ALPINE_VERSION: 3.14.0
                LUPUSMICHAELIS_IGOR_VERSION: 1.1.3
        image: lupusmichaelis/alpine:1.1.3

    alpine-dev:
        <<: *dev-env
        build:
            context: ./build/alpine-dev
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.3
        image: lupusmichaelis/alpine-dev:1.1.3

    ############################################################################
    # Web server
    #
    alpine-proxy:
        build:
            context: ./build/alpine-proxy
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
        image: lupusmichaelis/alpine-proxy:1.1.2

    alpine-lighttpd:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
        depends_on:
            - alpine
        image: lupusmichaelis/alpine-lighttpd:1.1.2

    alpine-lighttpd-secure:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
                LIGHTTPD_SECURE: enable
        depends_on:
            - alpine-lighttpd
        image: lupusmichaelis/alpine-lighttpd-secure:1.1.2

    alpine-lighttpd-proxy:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
                LIGHTTPD_PROXY: enable
        depends_on:
            - alpine-lighttpd
        image: lupusmichaelis/alpine-lighttpd-proxy:1.1.2

    alpine-lighttpd-secure-front:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
                LIGHTTPD_SECURE: enable
                LIGHTTPD_PROXY: enable
                LIGHTTPD_REWRITE: when-not-found
        depends_on:
            - alpine-lighttpd
        image: lupusmichaelis/alpine-lighttpd-secure-front:1.1.2

    alpine-lighttpd-front:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
                LIGHTTPD_PROXY: enable
                LIGHTTPD_REWRITE: when-not-found
        depends_on:
            - alpine-lighttpd
        image: lupusmichaelis/alpine-lighttpd-front:1.1.2

    alpine-lighttpd-proxy-single:
        build:
            context: ./build/alpine-lighttpd
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.2
                LIGHTTPD_PROXY: enable
                LIGHTTPD_REWRITE: always
        depends_on:
            - alpine-lighttpd
        image: lupusmichaelis/alpine-lighttpd-proxy-single:1.1.2

    alpine-apache:
        build:
            context: ./build/alpine-apache
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.3
        depends_on:
            - alpine
        image: lupusmichaelis/alpine-apache:1.1.3

    ############################################################################
    # PHP
    #
    alpine-php7:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
        depends_on:
            - alpine-dev
        image: lupusmichaelis/alpine-php7:1.1.2

    alpine-php7-fpm:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
                PHP_FPM: enable
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-fpm:1.1.2

    alpine-php7-composer:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
                PHP_COMPOSER: enable
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-composer:1.1.2

    alpine-php7-fpm-composer:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
                PHP_COMPOSER: enable
                PHP_FPM: enable
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-fpm-composer:1.1.2

    alpine-php7-fpm-composer:
        <<: *dev-env
        build:
            context: ./build/alpine-php7
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
                PHP_FPM: enable
                PHP_COMPOSER: enable
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-fpm-composer:1.1.2

    alpine-php8:
        <<: *dev-env
        build:
            context: ./build/alpine-php8
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
        depends_on:
            - alpine-dev
        image: lupusmichaelis/alpine-php8:1.1.2

    ############################################################################
    # MX
    #
    alpine-postfix:
        build:
            context: ./build/alpine-postfix
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
        environment:
            - LUPUSMICHAELIS_DEV_USER_ALIAS=kevin
            - LUPUSMICHAELIS_DEV_UID=${LUPUSMICHAELIS_DEV_UID?Please export LUPUSMICHAELIS_DEV_UID}
        image: lupusmichaelis/alpine-postfix:1.1.2

    alpine-postfix-mutt:
        build:
            context: ./build/alpine-postfix-mutt
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.2
        environment:
            - LUPUSMICHAELIS_DEV_USER_ALIAS=kevin
            - LUPUSMICHAELIS_DEV_UID=${LUPUSMICHAELIS_DEV_UID?Please export LUPUSMICHAELIS_DEV_UID}
        image: lupusmichaelis/alpine-postfix-mutt:1.1.2

    ############################################################################
    # Databases
    alpine-mariadb:
        build:
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.3
                LUPUSMICHAELIS_ALPINE_MARIADB_VERSION: 1.1.6
            context: ./build/alpine-mariadb
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
            - 'MYSQL_DATA_PATH=/var/lib/mysql'
        image: lupusmichaelis/alpine-mariadb:1.1.6
        restart: "no"

    alpine-redis:
        build:
            args:
                LUPUSMICHAELIS_ALPINE_VERSION: 1.1.3
                LUPUSMICHAELIS_ALPINE_REDIS_VERSION: 1.1.3
            context: ./build/alpine-redis
        image: lupusmichaelis/alpine-redis:1.1.3
        restart: "no"

    ############################################################################
    # Node's wonderland
    alpine-nodejs:
        <<: *dev-env
        build:
            args:
                LUPUSMICHAELIS_ALPINE_DEV_VERSION: 1.1.3
            context: ./build/alpine-nodejs
        depends_on:
            - alpine-dev
        environment:
            - LUPUSMICHAELIS_DEV_USER_ALIAS=kevin
            - LUPUSMICHAELIS_DEV_UID=${LUPUSMICHAELIS_DEV_UID?Please export LUPUSMICHAELIS_DEV_UID}
        image: lupusmichaelis/alpine-nodejs:1.1.3

    alpine-react:
        <<: *dev-env
        build:
            context: ./build/alpine-react
        depends_on:
            - alpine-nodejs
        image: lupusmichaelis/alpine-react:1.0.4

    alpine-react-ts:
        <<: *dev-env
        build:
            context: ./build/alpine-react-ts
        depends_on:
            - alpine-react
        image: lupusmichaelis/alpine-react-ts:1.0.4

    alpine-elm:
        <<: *dev-env
        build:
            args:
                LUPUSMICHAELIS_ALPINE_NODEJS_VERSION: 1.1.3
            context: ./build/alpine-elm
        depends_on:
            - alpine-nodejs
        environment:
            - LUPUSMICHAELIS_DEV_USER_ALIAS=kevin
            - LUPUSMICHAELIS_DEV_UID=${LUPUSMICHAELIS_DEV_UID?Please export LUPUSMICHAELIS_DEV_UID}
        image: lupusmichaelis/alpine-elm:1.1.3

# vim: ts=4:sw=4:et
