#!/bin/bash

yq()
{
	docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}

for imagetag in $(cat builder.docker-compose.yml | yq e '.services.*.image' -)
do
	image=$(echo $imagetag | cut -d':' -f1)
    docker tag "$imagetag" "$image:latest"
    docker push "$imagetag"
    docker push "$image:latest"
done
