#
#
# You need environment variables set on how to find repository and workshop directories
#

version: '3'

volumes:
    db:
        driver: local

services:
    alpine-elm-0.19:
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        image: mickael/alpine-elm-0.19
        restart: "no"

    bulma-sandbox:
        build:
            context: ./build/alpine-lighttpd
        container_name: bulma-sandbox
        image: mickael/bulma-sandbox
        ports:
            - 80
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw

    db:
        build: ./build/alpine-mariadb
        container_name: test-db
        environment:
            MYSQL_USER_NAME: dummy
            MYSQL_USER_HOST: '%'
            MYSQL_USER_PASSWORD: test
            MYSQL_USER_DATABASE: sandbox
        image: mickael/db
        ports:
            - 3306
        restart: "no"
        volumes:
            - ./conf/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf:ro

    go-lang:
        build:
            context: ./build/alpine-go-lang
    maria-db:
        image: mysql:5.7
        restart: always
        command: mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        volumes:
            - /data/maria-db:/var/lib/mysql

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pelpev2020', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10

    elm-sandbox:
        image: mickael/alpine-elm-0.19
        build:
            context: ./build/alpine-elm-0.19
            args:
                - UID=${UID?Please export UID}
                - GID=${GID?Please export GID}
                - USER_ALIAS=elm
        container_name: elm-sandbox

    node:
        image: mickael/debian-buster-node
        build:
            context: ./build/alpine-nodejs
            args:
                UID: ${UID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil

    elm-sandbox:
        container_name: elm-sandbox
        image: mickael/alpine-elm-0.19
        build:
            context: ./build/alpine-elm-0.19
            args:
                UID: ${UID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil
        depends_on:
            - node
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        restart: "no"

        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-rpg:
        container_name: elm-rpg
        image: mickael/alpine-elm-0.19
        restart: "no"
        build:
            context: ./build/alpine-elm-0.19
            args:
                UID: ${UID}
                USER: ${USER_ALIAS:-elm}
                HOME: /home
                ANVIL: /home/anvil
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-conway:
        container_name: elm-conway
        image: mickael/debian-elm-0.19
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway:/home/anvil:rw
        command: [ elm-live, src/Conway.elm]

    elm-rpg:
        container_name: elm-rpg
        image: mickael/alpine-elm-0.18
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw

    web:
        build: ./build/debian-jessie-apache2-php56
        container_name: test-web
        depends_on:
            - db
        image: mickael/web
        ports:
            - 80:80
        restart: "no"
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro
