#
#
# You need environment variables set on how to find repository and workshop directories
#

version: '3'

volumes:
    db:
        driver: local

services:
    web:
        container_name: test-web
        restart: "no"
        build: ./build/web
        depends_on:
            - db
        ports:
            - 80:80
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro

    db:
        container_name: test-db
        restart: "no"
        environment:
            MYSQL_USER_NAME: dummy
            MYSQL_USER_HOST: '%'
            MYSQL_USER_PASSWORD: test
            MYSQL_USER_DATABASE: sandbox
        build:
            context: ./build/db
            args:
                MYSQL_SYSUSER: mysql
                MYSQL_SYSGROUP: mysql
                MYSQL_DATA_PATH: /var/lib/mysql
                MYSQL_SECRET:

        ports:
            - 3306
        volumes:
            - ./conf/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf:ro

    elm-sandbox:
        container_name: elm-sandbox
        restart: "no"
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        build:
            context: ./build/elm
            args:
                UID: ${UID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-rpg:
        container_name: elm-rpg
        restart: "no"
        build:
            context: ./build/elm
            args:
                UID: ${UID}
                USER: ${USER_ALIAS:-elm}
                HOME: /home
                ANVIL: /home/anvil
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw

    elm-conway:
        container_name: elm-conway
        restart: "no"
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        build:
            context: ./build/elm
            args:
                - UID=${UID?Please export UID}
                - GID=${GID?Please export GID}
                - USER_ALIAS=elm
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway:/home/anvil:rw

    bulma-sandbox:
        container_name: bulma-sandbox
        restart: "no"
        build:
            context: ./build/lighttpd
        ports:
            - 80
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw
