version: '3'

volumes:
    db:
        driver: local

services:
    web:
        container_name: test-web
        restart: "no"
        build: ./build/web
        depends_on:
            - db
        ports:
            - 80:80
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro

    db:
        container_name: test-db
        restart: "no"
        environment:
            MYSQL_USER_NAME: dummy
            MYSQL_USER_HOST: '%'
            MYSQL_USER_PASSWORD: test
            MYSQL_USER_DATABASE: sandbox
        build:
            context: ./build/db
            args:
                MYSQL_SYSUSER: mysql
                MYSQL_SYSGROUP: mysql
                MYSQL_DATA_PATH: /var/lib/mysql
                MYSQL_SECRET:

        ports:
            - 3306
        volumes:
            - ./conf/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf:ro

    elm-tutorial:
        container_name: elm-tutorial
        restart: "no"
        build:
            context: ./build/elm
            args:
                USER: mickael
                HOME: /home/mickael
                ANVIL: /home/mickael/anvil
        volumes:
            - /home/mickael/Workshop/elm-tutorial:/home/mickael/anvil:rw

    elm-rpg:
        container_name: elm-rpg
        restart: "no"
        build:
            context: ./build/elm
            args:
                USER: mickael
                HOME: /home/mickael
                ANVIL: /home/mickael/anvil
        volumes:
            - /home/mickael/Workshop/elm-rpg:/home/mickael/anvil:rw

    elm-conway:
        container_name: elm-conway
        restart: "no"
        build:
            context: ./build/elm
            args:
                USER: mickael
                HOME: /home/mickael
                ANVIL: /home/mickael/anvil
        volumes:
            - /home/mickael/Workshop/elm-conway:/home/mickael/anvil:rw
