version: '3'

services:

    front:
        build:
            context: ./build/alpine-lighttpd-proxy

        image: lupusmichaelis/alpine-lighttpd-proxy

        depends_on:
            - back

    back:
        image: lupusmichaelis/alpine-php7-fpm
        build:
            context: ./build/alpine-php7-fpm
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

