##############################################################################
#
# Building images for publishing
#
##############################################################################

x-dev-env: &dev-env
    environment:
        - LP_DEV_UID=${LP_DEV_UID?Please export LP_DEV_UID}
        - LP_DEV_GID=${LP_DEV_GID?Please export LP_DEV_GID}
        - LP_DEV_USER_ALIAS=${LP_DEV_USER_ALIAS?Please export}
    restart: "no"

services:
    elm-conway:
        <<: *dev-env
        build:
            context: ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway
        image: lupusmichaelis/conway-game-of-life:1.0.0
