##############################################################################
#
# Building images
#
##############################################################################

version: '3.4'


x-dev-env: &dev-env
    env_file:
        - .env
    environment:
        - UID=${UID?Please export UID}
        - GID=${GID?Please export GID}
        - USER_ALIAS=${USER_ALIAS?Please export}
    restart: "no"

services:
    ############################################################################
    # Web design
    #
    bulma-sandbox:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd
        image: lupusmichaelis/bulma-sandbox
        ports:
            - 80
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw

    elm-sandbox:
        <<: *dev-env
        image: lupusmichaelis/alpine-elm

        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-conway:
        <<: *dev-env
        build:
            context: ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway
        image: lupusmichaelis/conway-game-of-life
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway:/home/anvil:rw

    elm-rpg:
        image: lupusmichaelis/alpine-elm
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw

    web-rtc:
        <<: *dev-env
        image: lupusmichaelis/alpine-nodejs:1.0.1
        ports:
            - "3000:3000"
        command:
            - npm
            - run
            - dev
        volumes:
            - ${WORKSHOP_DIR}/web-rtc:/home/anvil:rw
