##############################################################################
#
# Image builder, requires a populated .env file in this very file's directory,
# generated through ./gen-env.
#
##############################################################################

version: '3'

volumes:
    db:
        driver: local

services:
    ############################################################################
    # OSes
    #
    alpine:
        image: lupusmichaelis/alpine
        build:
            context: ./build/alpine
            args:
                - UID=${UID?Please export UID}
                - GID=${GID?Please export GID}
                - USER_ALIAS=${USER_ALIAS?Please export}

    ############################################################################
    # Web server
    #
    web-deb-jessie-ap2-php56:
        build: ./build/debian-jessie-apache2-php56
        image: lupusmichaelis/web-jessie-php56
        ports:
            - 80:80
        restart: "no"
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro

    ############################################################################
    # Web design
    #
    bulma-sandbox:
        build:
            context: ./build/alpine-lighttpd
        image: lupusmichaelis/bulma-sandbox
        ports:
            - 80
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw

    ############################################################################
    # PHP
    #
    alpine-php7:
        image: lupusmichaelis/alpine-php7
        build:
            context: ./build/alpine-php7
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    alpine-php7-fpm:
        image: lupusmichaelis/alpine-php7-fpm
        build:
            context: ./build/alpine-php7-fpm
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    alpine-php7-composer-dev:
        image: lupusmichaelis/alpine-php7-composer-dev
        build:
            context: ./build/alpine-php7-dev
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    ############################################################################
    # FTP server
    # XXX To audit
    #
    ftp:
        image: panubo/vsftpd:v1.0.0
        environment:
            - 'FTP_USER=ftp'
            - 'FTP_PASSWORD=ftp'

    ############################################################################
    # Skeleton for Go app
    go-lang:
        build:
            context: ./build/alpine-golang

    ############################################################################
    # Databases
    maria-db:
        build: ./build/alpine-mariadb
        image: lupusmichaelis/alpine-mariadb
        restart: "no"

    my-db:
        image: mysql:5.7
        restart: always
        command: mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        volumes:
            - /data/maria-db:/var/lib/mysql:rw # XXX
            - /var/run/mysqld/docker-mysqld.sock:/var/run/mysqld/mysqld.sock:rw

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pyolo', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10

    ############################################################################
    # Node's wonderland
    node:
        image: lupusmichaelis/alpine-nodejs
        build:
            context: ./build/alpine-nodejs
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    elm:
        image: lupusmichaelis/alpine-elm-0.19
        build:
            context: ./build/alpine-elm-0.19

    elm-sandbox:
        image: lupusmichaelis/alpine-elm-0.19
        restart: "no"

        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-conway:
        image: lupusmichaelis/conway-game-of-life
        build:
            context: ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway
            args:
                UID: ${UID?Please export}
                GID: ${GID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil
        restart: "no"

    elm-rpg:
        image: lupusmichaelis/alpine-elm-0.18
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw
