##############################################################################
#
# Building images
#
##############################################################################

version: '3.4'

volumes:
    db:
        driver: local

x-dev-env: &dev-env
    environment:
        - UID=${UID?Please export UID}
        - GID=${GID?Please export GID}
        - USER_ALIAS=${USER_ALIAS?Please export}

services:
    ############################################################################
    # OSes
    #
    alpine:
        <<: *dev-env
        image: lupusmichaelis/alpine
        build:
            context: ./build/alpine

    ############################################################################
    # Web server
    #
    web-deb-jessie-ap2-php56:
        build: ./build/debian-jessie-apache2-php56
        image: lupusmichaelis/web-jessie-php56
        ports:
            - 80:80
        restart: "no"
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro

    alpine-lighttpd:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd
        depends_on:
            - alpine
        environment:
            - USER_ALIAS=root
        image: lupusmichaelis/alpine-lighttpd

    alpine-lighttpd-secure:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd-secure
        depends_on:
            - alpine-lighttpd
        environment:
            - USER_ALIAS=root
        image: lupusmichaelis/alpine-lighttpd-secure

    alpine-lighttpd-proxy:
        <<: *dev-env
        build:
            context: ./build/alpine-lighttpd-proxy
        depends_on:
            - alpine-lighttpd
            - alpine-php7-fpm
        environment:
            - USER_ALIAS=root
            - BACKEND=alpine-php7-fpm
        image: lupusmichaelis/alpine-lighttpd-proxy

    ############################################################################
    # Web design
    #
    bulma-sandbox:
        build:
            context: ./build/alpine-lighttpd
        image: lupusmichaelis/bulma-sandbox
        ports:
            - 80
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw

    ############################################################################
    # PHP
    #
    alpine-php7:
        <<: *dev-env
        image: lupusmichaelis/alpine-php7
        build:
            context: ./build/alpine-php7

    alpine-php7-fpm:
        <<: *dev-env
        build:
            context: ./build/alpine-php7-fpm
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-fpm

    alpine-php7-composer-dev:
        <<: *dev-env
        build:
            context: ./build/alpine-php7-dev
        depends_on:
            - alpine-php7
        image: lupusmichaelis/alpine-php7-composer-dev

    ############################################################################
    # MX
    #
    alpine-postfix: # XXX
        image: lupusmichaelis/alpine-postfix
        build:
            context: ./build/alpine-postfix
            args:
                USER_ALIAS: ${USER_ALIAS?Please export}

    alpine-postfix-mutt: # XXX
        image: lupusmichaelis/alpine-postfix-mutt
        build:
            context: ./build/alpine-postfix-mutt
            args:
                USER_ALIAS: ${USER_ALIAS?Please export}

    ############################################################################
    # FTP server
    # XXX To audit
    #
    ftp:
        image: panubo/vsftpd:v1.0.0
        environment:
            - 'FTP_USER=ftp'
            - 'FTP_PASSWORD=ftp'

    ############################################################################
    # Skeleton for Go app
    go-lang:
        build:
            context: ./build/alpine-golang

    ############################################################################
    # Databases
    maria-db:
        build: ./build/alpine-mariadb
        image: lupusmichaelis/alpine-mariadb
        restart: "no"

    my-db:
        image: mysql:5.7
        restart: always
        command: mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        volumes:
            - /data/maria-db:/var/lib/mysql:rw # XXX
            - /var/run/mysqld/docker-mysqld.sock:/var/run/mysqld/mysqld.sock:rw

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pyolo', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10

    ############################################################################
    # Node's wonderland
    node:
        image: lupusmichaelis/alpine-nodejs
        build:
            context: ./build/alpine-nodejs
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    debian-buster-node:
        image: lupusmichaelis/debian-buster-node
        build:
            context: ./build/debian-buster-node
            args:
                UID: ${UID?Please export}
                USER_ALIAS: ${USER_ALIAS?Please export}

    elm:
        image: lupusmichaelis/alpine-elm
        build:
            context: ./build/alpine-elm

    elm-sandbox:
        image: lupusmichaelis/alpine-elm
        restart: "no"

        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-conway:
        image: lupusmichaelis/conway-game-of-life
        build:
            context: ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway
            args:
                UID: ${UID?Please export}
                GID: ${GID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil
        restart: "no"

    elm-rpg:
        image: lupusmichaelis/alpine-elm
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw
