#
#
# You need environment variables set on how to find repository and workshop directories
# ./gen-env
#

version: '3'

volumes:
    db:
        driver: local

services:
    alpine:
        image: lupusmichaelis/alpine
        build:
            context: ./build/alpine
            args:
                - UID=${UID?Please export UID}
                - GID=${GID?Please export GID}
                - USER_ALIAS=elm

    alpine-elm-0.19:
        image: lupsumichaelis/alpine-elm-0.19
        build:
            context: ./build/alpine-elm-0.19
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        restart: "no"

    bulma-sandbox:
        build:
            context: ./build/alpine-lighttpd
        image: lupusmichaelis/bulma-sandbox
        ports:
            - 80
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/bulma-sandbox/public_html:/var/www/localhost/htdocs:rw

    maria-db:
        build: ./build/alpine-mariadb
        environment:
            - MYSQL_ROOT_PASSWORD yolo
        image: lupusmichaelis/db
        ports:
            - 3306
        restart: "no"

    # XXX To audit
    ftp:
        image: panubo/vsftpd:v1.0.0
        environment:
            - 'FTP_USER=ftp'
            - 'FTP_PASSWORD=ftp'

    go-lang:
        build:
            context: ./build/alpine-golang
    my-db:
        image: mysql:5.7
        restart: always
        command: mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        volumes:
            - /data/maria-db:/var/lib/mysql:rw
            - /var/run/mysqld/docker-mysqld.sock:/var/run/mysqld/mysqld.sock:rw

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pyolo', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10

    node:
        image: lupusmichaelis/alpine-nodejs
        build:
            context: ./build/alpine-nodejs
            args:
                UID: ${UID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil

    elm-sandbox:
        container_name: elm-sandbox
        image: lupusmichaelis/alpine-elm-0.19
        build:
            context: ./build/alpine-elm-0.19
            args:
                UID: ${UID?Please export}
                USER: ${USER_ALIAS:-elm}
                HOME: /home/
                ANVIL: /home/anvil
        depends_on:
            - node
        environment:
            - UID=${UID?Please export UID}
            - GID=${GID?Please export GID}
            - USER_ALIAS=${USER_ALIAS:-elm}
            - WORKSHOP_DIR=${WORKSHOP_DIR?Please export WORKSHOP_DIR}
        restart: "no"

        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-rpg:
        image: lupusmichaelis/alpine-elm-0.19
        restart: "no"
#        build:
#            context: ./build/alpine-elm-0.19
#            args:
#                UID: ${UID}
#                USER: ${USER_ALIAS:-elm}
#                HOME: /home
#                ANVIL: /home/anvil
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-sandbox:/home/anvil:rw

    elm-conway:
        image: lupusmichaelis/debian-elm-0.19
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR?Please export WORKSHOP_DIR}/elm-conway:/home/anvil:rw
        command: [ elm-live, src/Conway.elm]

    elm-rpg:
        image: lupusmichaelis/alpine-elm-0.18
        restart: "no"
        volumes:
            - ${WORKSHOP_DIR}/elm-rpg:/home/anvil:rw

    web:
        build: ./build/debian-jessie-apache2-php56
        image: lupusmichaelis/web
        ports:
            - 80:80
        restart: "no"
        volumes:
            - ./conf/apache2/vhosts.conf:/etc/apache2/conf.d/vhosts.conf:ro
