##############################################################################
#
# Building images
#
##############################################################################

version: '3.4'

x-dev-env: &dev-env
    environment:
        - UID=${UID?Please export UID}
        - GID=${GID?Please export GID}
        - USER_ALIAS=${USER_ALIAS?Please export}
    restart: "no"

services:
    ############################################################################
    # Skeleton for Go app
    go-lang:
       build:
           context: ./build/alpine-golang
