#!/bin/bash -x

# Ygor, DEFINE!!! ##############################################################

YARN="npx yarn"

# Ygor, RUN!!!!!! ##############################################################
ygor-main()
{
    if [ "$#" -lt "1" ]
    then
        ygor-usage "$@"
    fi

    local component=$1; shift
    case $component in
        bs|byobu-session)
            ygor-byobu-session "$@"
            ;;

        d|docker)
            local action=$1; shift
            case $action in
                last-ip)
                    ygor-docker-last-ip
                    ;;
                ip)
                    ygor-docker-ip "$@"
                    ;;
                last-id)
                    ygor-docker-last-id
                    ;;
                *)
                    ygor-docker-usage "$@"
                    exit 2
            esac
            ;;

        e|elm)
            local action=$1; shift
            case $action in
                f|format)
                    ygor-elm-format "$@"
                    ;;
                fgc|format-git-cache)
                    ygor-elm-format-git-cache
                    ;;
                *)
                    ygor-elm-usage "$@"
                    exit 3
                    ;;
            esac
            ;;

        *)
            ygor-usage
    esac
}

ygor-usage()
{
    echo "Usage: \n"
    ygor-byobu-usage "$@"
    ygor-docker-usage "$@"
    exit 1
}

# Utils ########################################################################
ygor-die()
{
    echo "Dying on: '$1'"
    exit 255
}

# Byobu ########################################################################

ygor-byobu-usage()
{
    echo "\t$0 [bs|byobu-session]"
}

# Byobu session named after current working directory
ygor-byobu-session()
{
    byobu new -s $(basename $PWD) "$@" \
        || byobu attach -t $(basename $PWD) "$@"
}

# Docker #######################################################################
ygor-docker-usage()
{
    echo "\t$0 [d|docker] [last-ip|last-id]"
    echo "\t$0 [d|docker] ip <docker-id>"
}

ygor-docker-last-id()
{
    docker ps -ql
}

ygor-docker-last-ip()
{
    ygor-docker-ip $(ygor-docker-last-id)
}

ygor-docker-ip()
{
    docker inspect \
        --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
        "$@"
}

################################################################################
ygor-elm-usage()
{
    echo "\t$0 [e|elm] [f|format] <file>..."
    echo "\t$0 [e|elm] [fgc|format-git-cache]"
}

ygor-elm-format()
{
    $YARN elm-format --yes "$@"
}

ygor-elm-format-git-cache()
{
    files=$(git diff --name-only --cached | grep \.elm)
    if [[ ! -z "$files" ]]
    then
        ygor-elm-format $files
    fi
}

# Ygor, LIGHT IT UP!!! #########################################################
ygor-main "$@"
