##############################################################################
#
# Alien images
#
##############################################################################

services:
    ############################################################################
    # FTP server
    #
    ftp:
        image: panubo/vsftpd:v1.0.0
        environment:
            - 'FTP_USER=ftp'
            - 'FTP_PASSWORD=ftp'

    ############################################################################
    # Databases
    #
    my-db:
        image: mysql:5.7
        restart: always
        command: mysqld --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
        environment:
            - 'MYSQL_ROOT_PASSWORD=yolo'
        volumes:
            - /data/maria-db:/var/lib/mysql:rw

        healthcheck:
            test: ['CMD', 'mysqladmin' ,'ping', '-uroot', '-pyolo', '-hlocalhost']
            interval: 10s
            timeout: 20s
            retries: 10
